### ISSUE TITLE
Dynamic Canvas Size

### ISSUE THREAD

**Issue by ecroitoru** [net-art-uchicago/paintArtware1.0#20]
Change the canvas size when the window size changes.

**Comment by ecroitoru** [comment]
I will fix.

**Comment by nbriz** [comment]
in re:to ur question regarding the best spot in the code base to address this, u asked if it should go in canvas2d.js or artware.js, while there's no "right" answer, my suggestion would be to put a little bit of code in each.

so canvas2d.js is a "library" we're developing to make drawing onto our canvas easier (like a [swiss army knife](https://blademag.com/wp-content/uploads/officers-sports-knife-swiss-army-victorinox.jpg) of drawing tools) while artware.js is our "framework", responsible for managing the general architecture of the app && how all the pieces fit together.

this being the case, it makes the most sense that any EventListeners responding to changes in window sizes should probably be handled in artware.js, i'd put it the framework's [constructor](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Classes/constructor) (above or below the ["load" EventListener](https://github.com/net-art-uchicago/paintArtware1.0/blob/c6898f18247063f2732e6f805eacd11295aad378/js/libs/artware.js#L25-L35))

if all the code necessary for resizing the canvas could be handled in a single line of code, then that would be it... but, b/c u'll probably need to write a little bit of logic to handle this && b/c the act of resizing the canvas may be something others might want to do elsewhere in the project, it wouldn't be a bad idea to add a new static method to the canvas2d.js library which handles the actual resizing, something like `C2D.resize(width, height)`

u can then call that function inside the EventListner that u add to the artware.js constructor, something like:
```js
    window.addEventListener('resize', () => {
      const width = 1920
      const height = 1080
      C2D.resize(width, height)
    })
```

of course, u don't want to resize it to hardcoded values like 1920x1080, u'll want it to match the size of that main drawing area. take a look at this `createCanvas` method of the artware.js class to see how the width/height are initially calculated to match the size of the main drawing area (u can model ur code on that)

https://github.com/net-art-uchicago/paintArtware1.0/blob/c6898f18247063f2732e6f805eacd11295aad378/js/libs/artware.js#L152-L170
