### ISSUE TITLE
Rainbow Filter

### ISSUE THREAD

**Issue by lrmantovani10** [net-art-uchicago/paintArtware1.0#24]
Select opposite color of the one chosen by the user by subtracting the user's color from (255, 255, 255) -- pure white

**Comment by nbriz** [comment]
is this going to be a filter applied to all the pixels at once? or are u imagining it as a tool, where it's applied only to a set of pixels under the cursor as the user moves their mouse?

**Comment by lrmantovani10** [comment]
> is this going to be a filter applied to all the pixels at once? or are u imagining it as a tool, where it's applied only to a set of pixels under the cursor as the user moves their mouse?

On a second thought, this works much better as a rainbow filter... Thanks for the input!
