### ISSUE TITLE
sentiment classifer library method

### ISSUE THREAD

**Issue by ecroitoru** [net-art-uchicago/paintArtware1.0#28]
Add a method to the library that classifies sentiment of a given text.

**Comment by nbriz** [comment]
this sounds cool!
have u thought about where in the code base this functionality is going to go?

i imagine this is going to be functionality that others on the project can use right?  if so, don't forget that u'll need to document ur code as well, the same way we've got documentation for the framework && the C2D library in the wiki (this should go in the [/docs](https://github.com/matildeyang/paintArtware1.0/tree/main/docs) folder)

there's an approach known as "documentation driven development", where u first write the docs && then u write the actual code. this helps u think first in terms of what the best API for others might be && then use that as a sort of blue-print or guide for ur development

**Comment by ecroitoru** [comment]
Implemented into sentibot library.
