### ISSUE TITLE
image emotion classifier library method

### ISSUE THREAD

**Issue by lnealer** [net-art-uchicago/paintArtware1.0#30]
I want to add a method to the library that classifies and returns the emotion/facial expression in the given image. I want it to be compatible with camera data so that we can stream in the webcam footage and classify emotions in real time

**Comment by nbriz** [comment]
awesome!
this sounds thematically similar to @ecroitoru idea of a [sentiment classifer](https://github.com/net-art-uchicago/paintArtware1.0/issues/28), u both should chat (maybe on slack) about where to best place this code. it might necessitate the creation of a new library && it best to group these together.

like i mentioned on that issue, b/c this is code others are meant to use, don't forget that u'll need to document ur code as well, the same way we've got documentation for the framework && the C2D library in the wiki (this should go in the [/docs](https://github.com/matildeyang/paintArtware1.0/tree/main/docs) folder)

there's an approach known as "documentation driven development", where u first write the docs && then u write the actual code. this helps u think first in terms of what the best API for others might be && then use that as a sort of blue-print or guide for ur development
